---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.dotfiles

collections:
  - name: geerlingguy.mac
<<<<<<< Updated upstream
#  - name: community.general
#    version: "*"
=======
  - name: community.crypto
>>>>>>> Stashed changes
