---
- name: Generate a default OpenSSH keypair with ED25519.
  community.crypto.openssh_keypair:
    path: "{{ ansible_env.HOME }}/.ssh/{{ ssh_key_name }}"
    type: ed25519
    mode: 0600

- name: Symlink ssh client config.
  file:
    src: "{{ dotfiles_repo_local_destination }}/sshconfig"
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    state: link
